// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD50TgwhsuXR2kcDqUt3StbPh9azShaBDY',
    appId: '1:863787672814:web:95eadedaa9d0295475bfff',
    messagingSenderId: '863787672814',
    projectId: 'nepschat',
    authDomain: 'nepschat.firebaseapp.com',
    storageBucket: 'nepschat.appspot.com',
    measurementId: 'G-X6VXTSKDFN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcrR4y59SMtNsllyqzJjVVsL8swTkLipo',
    appId: '1:863787672814:android:f274277607b7407875bfff',
    messagingSenderId: '863787672814',
    projectId: 'nepschat',
    storageBucket: 'nepschat.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPltn5TvqzLHzRskIgjWbHRxDeamUY7ak',
    appId: '1:863787672814:ios:411d11e5b10a1fbb75bfff',
    messagingSenderId: '863787672814',
    projectId: 'nepschat',
    storageBucket: 'nepschat.appspot.com',
    iosClientId: '863787672814-25h16rc7v5kod1lde22g591i7bapri7e.apps.googleusercontent.com',
    iosBundleId: 'com.example.nepsChatProject',
  );


}
